name: weekly_menu_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^3.0.10
  flutter_tags: ^0.4.9
  intl: ^0.16.1
  expandable: ^2.2.3
  grouped_buttons: ^1.0.4
  dotted_border: ^1.0.4
  flutter_typeahead: ^1.8.0
  flutter_keyboard_visibility: ^0.7.0
  autocomplete_textfield: ^1.7.3
  provider: ^4.1.2
  path_provider: any
  uuid: ^2.0.4
  json_annotation: ^3.0.1
  flutter_date_pickers: ^0.0.6
  logger: ^0.9.2
  shared_preferences: ^0.5.8
  objectid: ^1.1.1
  flutter_data: ^0.5.17
  flutter_data_state: ^0.3.1
  equatable: ^1.2.3
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  json_serializable: ^3.3.0
  lombok: ^0.0.5
  meta: ^1.1.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Pacifico
      fonts:
          - asset: assets/fonts/Pacifico.ttf
    - family: ChunckFive
      fonts:
          - asset: assets/fonts/ChunkFive-Regular.otf
    - family: Milkshake
      fonts:
        - asset: assets/fonts/Milkshake.otf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages